spring:
  data:
    mongodb:
      uri: mongodb+srv://Sid:Test%4012345@cluster0.piwnh.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
  redis:
    host: redis-19291.c264.ap-south-1-1.ec2.redns.redis-cloud.com
    port: 19291
    password: Ssrjjm6atIgHH4gmwEZYWYtEjVPBnqbn
    # host: localhost
    # port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: weekly-sentiment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: net.engineeringdigest.journalApp.model
    properties:
      security:
        protocol: PLAINTEXT
#      sasl:
#        mechanism: PLAIN
#        jaas:
#          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='xxxxx' password='xxxxxxxxxxxxxx';
#      session:
#        timeout:
#          ms: 45000

  mail:
    host: smtp.gmail.com
    port: 587
    username: ssanap222@gmail.com
    password: areu wtyk mvmo rrze
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: 8080
  servlet:
    context-path:

weather:
  api:
    key: 4a2376fbcc7701844b067baf1da410f5
